2019-05-08 18:07:43,784 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-08 18:07:58,336 ERROR: Exception on /edit_profile [GET] [in /Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alexchui/Desktop/microblog/app/routes.py", line 82, in edit_profile
    form = EditProfileForm()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2019-05-08 18:08:38,751 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-08 18:08:43,709 ERROR: Exception on /edit_profile [GET] [in /Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/alexchui/Desktop/microblog/app/routes.py", line 82, in edit_profile
    form = EditProfileForm()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2019-05-08 18:13:06,470 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-08 18:15:04,741 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-09 03:50:28,896 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-09 03:50:38,124 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-09 13:10:33,609 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-09 13:26:38,398 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-09 13:27:25,215 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-09 13:29:04,996 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 03:54:24,100 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:00:40,040 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:04:26,954 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:06:10,691 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:07:59,600 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:12:11,570 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:13:45,927 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:14:24,553 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:17:56,733 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 04:18:48,385 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 05:09:46,067 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 05:10:05,647 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 06:09:11,572 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 06:20:10,387 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 15:20:34,390 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:44]
2019-05-10 15:43:53,661 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:46]
2019-05-10 15:59:28,546 INFO: Microblog startup [in /Users/alexchui/Desktop/microblog/app/__init__.py:46]
2019-05-10 15:59:34,310 ERROR: Exception on /login [GET] [in /Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alexchui/Desktop/microblog/app/routes.py", line 55, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/alexchui/Desktop/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/alexchui/Desktop/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/alexchui/Desktop/microblog/app/templates/login.html", line 26, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/alexchui/Desktop/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
